version: "3.9"
services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-%)dyx^e*s&t^fg$13x8^ctcc^bq10r-qfnoiqgp6)!7yy+nzqg"
      - "DJANGO_DEBUG=True"
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data:
